image: node:12.13.0-alpine

before_script:
  - npm i -g firebase-tools

stages:
  - deploy

deploy-functions:
  stage: deploy
  script:
    - cd functions
    - npm install
    - cd ..
    - firebase use --token $FIREBASE_TOKEN default
    - echo $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - FUNCTION_NAME=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME | sed 's/.*://'
    - firebase deploy --only "functions:$FUNCTION_NAME" --token $FIREBASE_TOKEN
    - firebase database:set /plugins plugin.json --confirm --token $FIREBASE_TOKEN
  when: manual
  only: [merge_requests]
